services:
  conquest-server:
    container_name: conquest-server
    image: conquest-server:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
      args:
        - ARCH=${ARCH}
    platform: linux/${ARCH}
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - TARGET=${TARGET}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=conquest-db
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_KEY=${ADMIN_KEY}
    depends_on:
      - conquest-db

  conquest-db:
    container_name: conquest-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=conquest_user
      - POSTGRES_PASSWORD=conquest_password
      - POSTGRES_DB=conquest_core
    volumes:
      - conquestdb:/var/lib/postgresql/data

volumes:
  conquestdb:
    name: conquest-data