name: Build and Deploy to Remote Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build --build-arg TARGET=production --build-arg ARCH=arm64 -t ${{ secrets.DOCKER_USERNAME }}/conquest-server:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/conquest-server:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose.yml to remote server
        run: scp ./docker-compose.yml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}

      - name: Deploy on remote server
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.REMOTE_PATH }}
            sed -i 's|${{ secrets.DOCKER_USERNAME }}/conquest-server:latest|${{ secrets.DOCKER_USERNAME }}/conquest-server:${{ github.sha }}|g' docker-compose.yml
            docker compose down
            docker compose pull
            docker compose up -d
          EOF